### What is Tensor?
A tensor is a physical entity that can be characterized by magnitude and multiple directions. 

In [34]:
# importing the required libraries

import tensorflow as tf

In [35]:
# initializing the constants
x1 = tf.constant([1, 2, 3, 4])
x2 = tf.constant([5, 6, 7, 8])

In [37]:
#multiply
result = tf.multiply(x1, x2)

print (result)

tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)


## A little bit complex example

### Loading th MNIST dataset, which is already present in the keras libraries

In [22]:
from tensorflow.keras.datasets import fashion_mnist

mnist = fashion_mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()

#converting the samples from integers to floating-point numbers

x_train, x_test = x_train/255.0, x_test/255.0

print (x_train, x_test)


[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]] [[[0. 0. 0

### Building the sequential model by stacking layers by choosing optimizer and loss function for training

In [23]:
model = tf.keras.models.Sequential(
    [tf.keras.layers.Flatten(input_shape=(28, 28)), 
    tf.keras.layers.Dense(128, activation = 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)])

In [24]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.6215282 ,  0.05453612,  0.7274628 , -0.5026709 ,  0.46836096,
        -1.2439388 ,  0.9960353 , -0.26266104, -0.00821025, -0.06901443]],
      dtype=float32)

### Converting above logits to probabilities for each class

In [25]:
tf.nn.softmax(predictions).numpy()

array([[0.1445492 , 0.08199251, 0.16070247, 0.04696586, 0.12402123,
        0.02237967, 0.21021421, 0.05970589, 0.07700586, 0.0724631 ]],
      dtype=float32)

### Loss Function using cross entropy calculation

In [26]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits = True)

In [28]:
loss_fn(y_train[:1], predictions).numpy()

2.624678

In [29]:
model.compile(optimizer = 'adam', loss = loss_fn, metrics = ['accuracy'])

In [30]:
model.fit(x_train, y_train, epochs = 5)


Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.5357 - accuracy: 0.8126
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4026 - accuracy: 0.8549
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3652 - accuracy: 0.8675
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3460 - accuracy: 0.8734
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3285 - accuracy: 0.8796


### Testing the performance of the model on the test-set

In [31]:
model.evaluate(x_test, y_test, verbose =2)

313/313 - 0s - loss: 0.3510 - accuracy: 0.8724


[0.35100677609443665, 0.8723999857902527]

### Returning the probability of the model

In [32]:
probability_model = tf.keras.Sequential([model, tf.keras.layers.Softmax()])

In [33]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.70984913e-05, 1.35960107e-07, 6.81261440e-07, 1.00518139e-06,
        2.12835266e-06, 4.46370617e-02, 6.84958195e-06, 4.78531271e-02,
        1.04025014e-04, 9.07377779e-01],
       [7.20335636e-04, 3.33749561e-08, 9.77513254e-01, 3.36423199e-07,
        8.30146018e-03, 6.98189946e-15, 1.34626022e-02, 4.31440594e-15,
        2.10654071e-06, 1.42399032e-13],
       [1.06809432e-06, 9.99998331e-01, 8.18383938e-08, 4.05405956e-07,
        9.40936005e-08, 1.60161578e-10, 1.29451827e-08, 3.55355971e-16,
        1.02453171e-10, 2.83876773e-14],
       [3.16607071e-07, 9.99985218e-01, 1.09788594e-07, 1.42809204e-05,
        4.26788596e-08, 4.87422269e-10, 1.07925118e-08, 2.16605317e-17,
        4.31165346e-11, 3.85055757e-14],
       [1.54354021e-01, 1.39318974e-04, 5.29151149e-02, 1.07390189e-03,
        6.82443706e-03, 6.07825714e-05, 7.81798720e-01, 4.04262573e-05,
        2.77643278e-03, 1.67646176e-05]], dtype=float32)>

# A Simple Model of ANN in Tensor Flow